function db = makeDBForPaper1(db,mode)
if ~exist('mode','var')||isempty(mode)
    mode = 'createDB';
end
%% Create analyses for paper1
dbName = 'bsPaper1';
dbSavePath = '\\132.239.158.169\datanetOutput';
db.savePath = dbSavePath;
switch mode
    case 'createDB'
        %% new mon 
        ID=0; % neuronID
        ID = ID+1;        
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1368]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1370:1373] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
%                 [1374] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullAndQuatC_binSpat';...
            [1377:1383]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [1384] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            [1386] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr256';...
            [1388:1389]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1391:1396] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn_good';...
            });
        
        ID=ID+1; %% 2
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1340:1341]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 3
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1207:1208]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1210:1211]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1213:1215]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [1218]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            [1220]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr256';...
            [1222]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [1227:1233]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [1234:1235]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            [1239]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128HalfC_binSpat';...
            [1241]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128QuatC_binSpat';...
            });
        
        ID=ID+1; %% 4
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1525]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1527:1528]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 5
        awake = 0; %% 1
        subj='408'; thrV=[-0.2 Inf 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1512]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1514:1520]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [1521:1522]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            });
        
        ID=ID+1; %% 6
        awake = 0; %% 1
        subj='408'; thrV1=[-Inf 0.1 2];thrV2=[-Inf 0.03 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1479]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'sfFF';...
            [1481:1486]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'bin6Deg';...
            [1487:1488]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'sfSmall';...
            [1490:1497]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'bin3Deg';...
            %     [1499:1500]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'aSum256FullAndQuatC_binSpat';...
            [1502:1503]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'cntr256_small';...
            });
        
        ID=ID+1; %% 7
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.07 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1430:1432]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1434:1440]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            %     [1441:1442]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullAndQuatC_binSpat';...
            [1444:1445]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            [1447:1449]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1451:1453]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            [1456:1457]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1459:1470]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 8
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1320:1327]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 9
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1304:1308]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [1309]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [1311]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            [1313]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr256';...
            %     [1315]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullAndQuatC_binSpat';...
            });
        
        ID=ID+1; %% 10
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1186:1190]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [1191]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 11
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [982:986]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [987]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [992:996]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 12
        awake = 0; %% 1
        subj='408'; thrV=[-0.10 Inf 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [940]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [942:948]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [949:950]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [952:953]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [955]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            %     [957]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullAndQuatC_binSpat';...
            });
        
        ID=ID+1; %% 13
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [841]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [844:849]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [850]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr256';...
            [852]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            });
        
        ID=ID+1; %% 14
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [891]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [893:897]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [898:904]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [905:906]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [908:909]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [911:912]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256HalfC_binSpat';...
            %     [916]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullAndQuatC_binSpat';...
            });
        
        ID=ID+1; %% 15
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [876]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [878:885]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 16
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.07 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [669]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [680:681]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [683:684]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC_binSpat';...
            [686:687]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128QuatC_binSpat';...
            [689:690]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC_binSpat';...
            [671:674 676:678 694:700]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [703:704]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            [709:710]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            [712:723]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn1';...
            [724:731]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn2';...
            [734]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            });
        
        ID=ID+1; %% 17
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.07 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [625 633]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [627:631]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [634:635]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            });
        
        ID=ID+1; %% 18
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [607:610]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [611:614]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [615]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [617]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [619:620]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr256FF';...
            });
        
        ID=ID+1; %% 10
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [598:602]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [595 596 603]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 20
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [556:557]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [559]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 21
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [514:515]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 22
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [384]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [388:395]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [386 396 397]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [398:399]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [401:403]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [404:405]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512FF';...
            [406:407]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            });
        
        ID=ID+1; %% 23
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [373 374]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [375:376]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [378 379]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 24
        awake = 0; %% 1
        subj='408'; thrV=[-0.1 Inf 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [349:351]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [352:353]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 25
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [363:364]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [365:366]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 26
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [284:286]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [287:295]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [296:299]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [300:302]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [303:305]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [306:308]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [309:312]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr512';...
            [319:321]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256HalfC_binSpat';...
            [322:326]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [327:328]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            %     [330:332]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC_binSpat';...
            %     [333:335]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128QuatC_binSpat';...
            });
        
        ID=ID+1; %% 27
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [236]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [238]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [277:282]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 28
        awake = 0; %% 1
        subj='408'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [94:100]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [105:108]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn1';...
            [116:120]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn2';...
            });
        
        ID=ID+1; %% 29
        awake = 0; %% 1
        subj='409'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [61:62]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [63:65]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [68:70]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 30
        awake = 0; %% 1
        subj='409'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [93:94]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [95:99]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [102]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmallFullC_binSpat';...
            [104]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'contrast256Small_binSpat';...
            });
        
        ID=ID+1; %% 31
        awake = 0; %% 1
        subj='409'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [84]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [86:91]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 32
        awake = 0; %% 1
        subj='409'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [61:62]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [63:65]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [68:72]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [73:75]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            });
        
        ID=ID+1; %% 33
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [381]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [383]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [385:391]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [392:393]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC_binSpat';...
            });
        
        ID=ID+1; %% 34
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [362:363]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [365:372]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 35
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [346]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [348]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [350:352]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 36
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.1 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [191:192]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [194:201]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [204:205]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_manual';...
            [207:208]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_manual';...
            [211:217]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg_changedPos?';...
            });
        
        ID=ID+1; %% 37
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [60:65]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [66]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [68:69]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [71]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            });
        
        ID=ID+1; %% 38
        awake = 0; %% 1
        subj='407'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [31]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [35]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [37:42]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [43:44]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 39
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [909:911]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [913:914]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [918:920]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 40
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [869:870]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [872]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [874:875]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 41
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [854]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [856]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [858:863]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [865]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum';...
            });
        
        ID=ID+1; %% 42
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.05 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [823]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [825]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [827:830]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [831:833]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [835:836]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [840:844]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 43
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.03 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [789:790]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [792]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [794:798]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [799]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [801]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            [803 804]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC_binSpat';...
            [806 807]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128QuatC_binSpat';...
            [812:820]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 44
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.05 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [741 742]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [744]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 45
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.05 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [722]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [724]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [726:728]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [730 731]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'a256FullC';...
            [733 734]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'a256QuatC';...
            [736]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'a256QuatC?';...
            });
        
        ID=ID+1; %% 46
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [708]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [710]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [712:716]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [717 718]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            });
        
        ID=ID+1; %% 47
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.05 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [683]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [685]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [687:689]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });

        ID=ID+1; %% 48
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.2 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [650 651]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [653]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [655:659]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [660 661]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            });
        
        ID=ID+1; %% 49
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.2 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [638]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [640:645]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [646]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 50
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [610:613]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [618:620]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'contrast512';...
            [640:642]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [625:627]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_manual';...
            [629 630]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_manual';...
            });
        
        ID=ID+1; %% 51
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [579]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [581]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [583:589]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [590]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            });
        
        ID=ID+1; %% 52
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [534]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [536:541]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [542:543]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [557 558]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 53
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.02 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [475]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [477:482]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            });
        
        ID=ID+1; %% 54
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [465 466]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [468:471]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [472:473]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 55
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.02 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [447]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [449:452]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [455]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC_binSpat';...
            [457]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256QuatC_binSpat';...
            });
        
        ID=ID+1; %% 56
        awake = 0; %% 1
        subj='405'; thrV1=[-Inf 0.1 3];thrV2=[-Inf 0.02 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [411 413]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'trf';...
            [415]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'sf';...
            [417:424]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'trf';...
            [427:432]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'bin6Deg';...
            [433]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'sfFF';...
            [435]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'sfSmall';...
            });
        
        ID=ID+1; %% 57
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3]; included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [372]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [374:378]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [379]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [382]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr';...
            [384:395]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            [397]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            });
        
        ID=ID+1; %% 58
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.1 3];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [344 345]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [347:352]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [353 354]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF';...
            [356]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128FullC';...
            [358]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128QuatC';...
            [360]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum128HalfC';...
            [362]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC';...
            [364]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'aSum256FullC';...
            [366]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'contrast';...
            [368:370]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin3Deg';...
            });
        
        ID=ID+1; %% 59
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.2 3];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [305:307]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [317]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [319:324]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg';...
            [326 328]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6Deg after rotn.';...
            });
        
        ID=ID+1; %% 60
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.06 3];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [289:294]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8';...
            });
        
        ID=ID+1; %% 61
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.08 3];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [244 245]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [247 248]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfFF_so_weird';...
            [261 271]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8';...
            });

        ID=ID+1; %% 62
        awake = 0; %% 1
        subj='405'; thrV=[-Inf 0.2 3];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [220]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [222:227]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8';...
            });

        ID=ID+1; %% 63
        awake = 0; %% 1
        subj='405'; thrV1=[-Inf 0.1 2]; thrV2=[-Inf 0.2 2];included=1;channels = 1;mon='WestinghouseL2410NM';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [69 70]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV1,awake,'trf';...
            [72:78]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'bin6X8';...
            [103:113]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'bin12X16';...
            [79 80]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'sfFF';...
            [85:88]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'sfSmall';...
            [89]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'cntr';...
            [91:93]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'radFullC';...
            [99 100]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'radFullC';...
            [94:97]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'radQuatC';...
            [114:119]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV2,awake,'ffgwn1';...
            });
        
        
        % old mon
        ID=ID+1; % 64 
        awake = 0; %% 1
        subj='389-old'; thrV=[-Inf 0.5 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [7:11]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf. good sort';...
            [13:19]  ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8. good.';...
            });
        
        ID=ID+1; %% 65
        subj='389-old'; thrV=[-Inf 0.2 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [21]    ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf. decent sort';...
            [23:26] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8. spatial at bottom.';...
            [29]    ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf. unclear peak in sftuning';...
            });
        
        ID=ID+1; %% 66
        subj='389-old'; thrV=[-0.15 Inf 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [45:50]    ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8 poor';...
            });
        
        ID=ID+1; % 67
        subj='389-old'; thrV=[-0.2 Inf 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [55:58] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'good spatial. center and surround';... %removin this because messed up
%             [60:61] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rC100';...
%             [62:63] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rC80';...
            [65:67] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8. still visible.';...
            });
        
        ID=ID+1; % 68
        subj='389-old'; thrV=[-Inf 0.15 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [72:76] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rf across multiple squares';...
%             [78] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rC100';...
%             [80] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rC60';...
            [82:84] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [85:87] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'12X16 after moving';...
            });
        
        ID=ID+1; % 69
        subj='389'; thrV=[-Inf 0.2 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [6] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [8:10] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [11:13] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8';...
            [14:17] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin12X16';...
            });
        
        ID=ID+1; % 70
        subj='389'; thrV=[-Inf 0.5 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [20] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [22:24] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [25:27] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8';...
            [28:35] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin12X16';...
            });

        ID=ID+1; % 71
        subj='389'; thrV=[-Inf 0.3 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [94:98] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [99:105] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [106:112] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin6X8. slow waveforms. but potentially salvageable';...
            [115:117] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            });

        ID=ID+1; % 73
        subj='389'; thrV=[-Inf 0.3 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [526] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [528 535] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin12X16';...
            [536:537] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfLarge';...
            [540:541] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sfSmall';...
            [543] ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'cntr';...
            });
        
        % other units exist but do not contain sf data

        ID=ID+1; % 75
        subj='375'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [393:396]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [398:400]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf likes high';...
            [402:405]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [407:411]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8. poor';...
            });

        ID=ID+1; % 76
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [590:593]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [595:606]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'decent spatial. incomplete boundary';...
            });
        
        
        ID=ID+1; % 77
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [758:761]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn. really clean';...
            [763:764]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [766:769]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'radius. shows suppression';...
            [773:775]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'12X16. shows clear boundaries';...
            [777:778]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'or. unimpressive';...
            [785:794]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8. shows centre and weak surround';...
            });

        
        ID=ID+1; % 78
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1182]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [1184:1187]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin...kinda weak';...
%             [1200:1201]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rad.shows suppression';...
%             [1203]        ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rad.reduced ctr.reduced supp';...
            });
 
                
        ID=ID+1;% 79
        subj='375'; thrV=[-0.2 Inf 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1210]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1212:1213]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf. likes large gratings';...
            [1214:1217]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
%             [1235:1236]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'or1024. unimpressive';...
            });
 

        ID=ID+1; % 80
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1277: 1281 1285 1286]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'ffgwn';...
            [1283]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [1294:1297]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin';...            
            });


        ID=ID+1;% 81
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1350:1351]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf. ylike?';...
            [1353:1359]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6X8.only at bottom';...
            [1361]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            });
        
        ID=ID+1;% 82
        subj='375'; thrV=[-0.2 0.2 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1366]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1368]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            [1370:1374]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6x8. at bottom. but complete';...
            [1386:1392]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'6x8. more centered';...
%           other types of trials exist here
            });
        
        ID=ID+1;% 83
        subj='375'; thrV=[-0.2 0.2 1]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1404:1406]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1407:1408]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
            });

       
        ID=ID+1;%% 84
        subj='375'; thrV=[-Inf 0.2 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1663:1665]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf.likes 8Hz';...
            [1668:1669]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'bin.poor';...
            [1671:1672]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf.likes small gratings';...
            [1674:1675]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'contrast.look at f0';...
%             [1686:1687]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rad64C100';...
%             [1688:1689]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'rad64C80';...
            });
      
        ID=ID+1;% 85
        subj='375'; thrV=[-0.25 Inf 2]; included=1;channels = 1;mon = 'ViewSonicPF790-VCDTS21611';
        sortQuality = NaN; eyeQuality = NaN; analysisQuality = NaN;         
        rigState = NaN; ampState = NaN;
        db=db.addSingleUnit(subj,ID,channels,mon,'',{...
            [1760]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'trf';...
            [1763]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'sf';...
%             [1765]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'radC80PPC128';...
%             [1767]   ,sortQuality,eyeQuality,analysisQuality,rigState,ampState,included,thrV,awake,'radC60PPC128';...
            });
%         

    case 'latest'
        
        db = db.load('bsPaper1_20120329T153636'); % All inclusive with sensitivity.

end

end
