db=addMorePmmNeurons(db,lastUsedID)

%set it
ID=lastUsedID;

%now start adding
ID=ID+1;
subj = '164'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [591:648],NaN,included,thrV,'spatial bin';...
    [654:680],NaN,included,thrV,'bipartiteLoc=0.9';...
    [692:730],NaN,included,thrV,'bin'});

ID=ID+1;
subj = '131dev'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [132:139],NaN,included,thrV,'unknown'});

ID=ID+1;
subj = '131dev'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [184],NaN,included,thrV,'TRF';...
        [264:320],NaN,included,thrV,'off screen?';...
        [363:378],NaN,included,thrV,'spatial sta';...
        [382:393],NaN,included,thrV,'small sta'});
    

ID=ID+1;
subj = '131dev4'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [40:181],NaN,included,thrV,'many stims, iso off at trial 70'})

ID=ID+1;
subj = '262'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [34:41],NaN,included,thrV,'ffgwn - has temporal STA';...
    [70],NaN,included,thrV,'gratingsSF';...
    [118:123],NaN,included,thrV,'spatial binary'})

ID=ID+1;
subj = '261'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [40],NaN,included,thrV,'sf'})
db.data{db.numNeurons}=db.data{db.numNeurons}.addComment('cell range [39 to 77]');

ID=ID+1;
subj = '261'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [114:116 118:121],NaN,included,thrV,'ffgwn';...
    [117],NaN,included,thrV,'grating'})

ID=ID+1;
subj = '261'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [181:185 187:188 197:200],NaN,included,thrV,'ffgwn';...
    [205],NaN,included,thrV,'gratings'})

ID=ID+1;
subj = '261'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [243:250 271:272],NaN,included,thrV,'ffgwn';...
    [262],NaN,included,thrV,'sf'})

ID=ID+1;
subj = '261'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [288:293],NaN,included,thrV,'ffgwn';...
    [294],NaN,included,thrV,'sf';...
    [324:332],NaN,included,thrV,'bin grid, 3x4';...
    [341:346 351:359 365],NaN,included,thrV,'bin grid, 6x8'}):
db.data{db.numNeurons}=db.data{db.numNeurons}.addComment('347 has issues sorting');

ID=ID+1;
subj = '138'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [8:19],NaN,included,thrV,'ffwgn while rat awak and no duc messing'})

ID=ID+1;
subj = '138'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [25:29],NaN,included,thrV,'ffwgn';...
    [37:47],NaN,included,thrV,'sf,very broad drives it'})

ID=ID+1;
subj = '249'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [42 43:50 60:70],NaN,included,thrV,'ffgwn';...
    [78 95],NaN,included,thrV,'gratings'})
        
ID=ID+1;
subj = '249'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [160:185],NaN,included,thrV,'ffgwn';...
    [192:225],NaN,included,thrV,'wn';...
    [187:190],NaN,included,thrV,'gratings'})


ID=ID+1;
subj = '249'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [],NaN,included,thrV,'';...
    [],NaN,included,thrV,'';...
    [],NaN,included,thrV,''})

ID=ID+1;
subj = 'xxx'; thrV=[-0.05 Inf 2]; included=1;
db=db.addSingleUnit(subj,ID,'',{...
    [],NaN,included,thrV,'';...
    [],NaN,included,thrV,'';...
    [],NaN,included,thrV,''})



%subjectID = '303';cellBoundary={'trialRange',[1 27 ]}  ignored... what trial breaks?
