function p=getPositionInBregmaCoordinates(eventdata,which,levelToTopOfBrain,nonPresentValue)
% eventdata- as generated by physiologySever event logger
% which - a logical (or index) into which events

if ~exist('levelToTopOfBrain','var') || isempty(levelToTopOfBrain)
    levelToTopOfBrain=false;
    
end

if ~exist('nonPresentValue','var') || isempty(nonPresentValue)
    %nonPresentValue=1; % would floast the data above the brain, so you see it
    nonPresentValue=nan;
end

raw_position=vertcat(eventdata(which).position);
surgeryA=vertcat(eventdata(which).surgeryAnchor);
surgeryB=vertcat(eventdata(which).surgeryBregma);
A=vertcat(eventdata(which).currentAnchor);

APOrientation = [];
MLOrientation = [];
surgeryAPOrientation = [];
surgeryMLOrientation = [];
% going to use the orientations of the AP and ML axes and trying to fit
% them to absolute orientations. down is positive. left is positive.
% (bregma coords)
whichEvents = find(which);
for i = 1:length(which)
    if isfield(eventdata(which(i)),'APOrientation') && ~isempty(eventdata(which(i)).APOrientation)
        APOrientation(i) = 2*double(~eventdata(whichEvents(i)).APOrientation)-1;
        MLOrientation(i) = 2*double(~eventdata(whichEvents(i)).MLOrientation)-1;
        surgeryAPOrientation(i) = 2*double(~eventdata(whichEvents(i)).surgAPOrientation)-1;
        surgeryMLOrientation(i) = 2*double(~eventdata(whichEvents(i)).surgMLOrientation)-1;
    else % backward compatibility
        APOrientation(i)  = 1;
        MLOrientation(i) = 1;
        surgeryAPOrientation(i) = 1;
        surgeryMLOrientation(i) = 1;
    end
end
%get translation from surgery
translation=surgeryB-surgeryA;  % vector surg.anchor -> surg.bregma

translation(:,1)=surgeryAPOrientation'.*translation(:,1); 
translation(:,2)=surgeryMLOrientation'.*translation(:,2); 
translation(:,3) = -translation(:,3);

% calculate current position
current_offset=(raw_position-A); % vector anch -> curr
%convert from rig1's inverted position (posterior positive; left postive) to matlabs axis (anterior positive; right positive)
current_offset(:,1)=APOrientation'.*current_offset(:,1); % flip AP
current_offset(:,2)=MLOrientation'.*current_offset(:,2); % flipML
current_offset(:,3)=-current_offset(:,3); % flipML

p=translation - current_offset;  % vec b-c (current from bregma)= b-a (anchor from bregma:surgery field ) - (c-a current from anchor)

if levelToTopOfBrain
    % this has the dangerous effect of ignoring brain curvature
    % or doing some strange normalization with respect to
    % cortical surface bulging...
    % but can be used to clean up data with "messy z"
    % if every penetration reliably has a "top of brain event"
    
    % set the top at -0.7mm (paxinos and watson, ctx surface relative to bregma, roughly above LGN)
    newTOB=-0.7;
    
    %find TOB z value reading for each penetration (called 'TOBraw')
    allPenIDs=find(~cellfun('isempty',{eventdata.penetrationNum}));
    TOB=ismember({eventdata.eventType},{'top of brain'});
    pen=[eventdata.penetrationNum];
    pens=unique(pen);
    TOBraw=nan(1,length(pens));
    for i=1:length(pens)
        %find the TOB for this penetration
        thisPen=[eventdata.penetrationNum]==pens(i);
        if length(thisPen)~=length(allPenIDs)
            error('expected to be the same... violates logic if not')
        end
        thisTOB=ismember({eventdata(allPenIDs(thisPen)).eventType},{'top of brain'});
        thisTOF=ismember({eventdata(allPenIDs(thisPen)).eventType},{'top of fluid'}); % not used currently!
        if any(thisTOB)  % if there is a top of brain this penetration, then
            TOBIndLocal=max(find(thisTOB)); %use the last observation if many this penetration
            eventIDsThisPen=find(thisPen);
            TOBIndGlobal=allPenIDs(eventIDsThisPen(TOBIndLocal));
            TOBraw(i)=eventdata(TOBIndGlobal).position(1,3); % save it for the next calculation
        end
    end
    
    %find TOB for each event that will be plotted
    positionsToChange=find(which & ~cellfun('isempty',{eventdata.penetrationNum}));
    TOBforEachEvent=TOBraw([eventdata(positionsToChange).penetrationNum]);
    
    
    for i=1:length(positionsToChange)
        if isnan(TOBforEachEvent(i))
            p(i,3)=nonPresentValue+rand/2;
            %data with out "top of brain event, can be placed
            %above the brain, with some scatter, but is nan'd by default
        else
            p(i,3)= eventdata(positionsToChange(i)).position(1,3)-TOBforEachEvent(i)+newTOB;
        end
    end
end