db = neuronDB('bsNeurons');
% db.save;
% db.mode = 'onlyDetectAndSort';
% db.process('all');
db.save;
% %%
% db = neuronDB('bsNeurons');
% db.mode = 'onlyInspectInteractive';
% db.process(1);
% %% some of the thresholds were messed up
% clear all
% db = neuronDB('bsNeurons');
% ID = 1;
% awake = 0; %%
% subj='389'; thrV=[-Inf 0.5 2]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [7:11]  ,NaN,included,thrV,awake,'trf. good sort';...
%     [13:16] ,NaN,included,thrV,awake,'clean spatial.6X8';...
%     [17:18] ,NaN,included,thrV,awake,'12X16 still visible';...
%     },[],true);
% 
% ID = 2;
% subj='389'; thrV=[-Inf 0.2 2]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [21]    ,NaN,included,thrV,awake,'trf. decent sort';...
%     [23:27] ,NaN,included,thrV,awake,'6X8. spatial at bottom.';...
%     [29]    ,NaN,included,thrV,awake,'sf. unclear peak in sftuning';...
%     },[],true);
% 
% ID = 12;
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1128:1131]   ,NaN,included,thrV,awake,'trf';...
%     [1132]        ,NaN,included,thrV,awake,'sf.look at f0 vs f1';...
%     [1135:1136]   ,NaN,included,thrV,awake,'ffgwn.weak effect';...
%     },[],true);
% 
% ID = 13;
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1182]        ,NaN,included,thrV,awake,'sf.looks weird!';...
%     [1184:1194]   ,NaN,included,thrV,awake,'6x8.largerf at bottom';...
%     [1200:1201]   ,NaN,included,thrV,awake,'rad.shows suppression';...
%     [1203]        ,NaN,included,thrV,awake,'rad.reduced ctr.reduced supp';...
%     },[],true);
% 
% ID = 15;
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1277:1286]   ,NaN,included,thrV,awake,'ffgwn';...
%     [1283]   ,NaN,included,thrV,awake,'sf. likes small ppc';...
%     [1294:1297]   ,NaN,included,thrV,awake,'6X8';...
%     [1298:1301]   ,NaN,included,thrV,awake,'6X8.changed location a little bit';...
%     [1305]   ,NaN,included,thrV,awake,'rad. no suppression';...
%     },[],true);
% 
% ID = 22;
% subj='375'; thrV=[-Inf 0.2 2]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1657]   ,NaN,included,thrV,awake,'trf.likes 8Hz';...    
%     [1663:1665]   ,NaN,included,thrV,awake,'trf.likes 8Hz';...
%     [1671:1672]   ,NaN,included,thrV,awake,'sf.likes small gratings';...    
%     [1674:1675]   ,NaN,included,thrV,awake,'contrast.look at f0';...    
%     [1686:1687]   ,NaN,included,thrV,awake,'rad64C100';...
%     [1688:1689]   ,NaN,included,thrV,awake,'rad64C80';...
%     },[],true);
% db.save;
%% redetecting and sorting
% IDs = [1 2 12 13 15 22];
% db = neuronDB('bsNeurons');
% db.mode = 'onlyDetectAndSort';
% db.process(IDs);
%% inspecting
% db.mode = 'onlyInspectInteractive';
% db.process(19:23)
%% something is barfing in neuron 5
% db = neuronDB('bsNeurons');
% ID=5;
% subj='375'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [393:397]   ,NaN,included,thrV,awake,'ffgwn';...
%     [398:400]   ,NaN,included,thrV,awake,'trf likes high';...
%     [402:404]   ,NaN,included,thrV,awake,'sf';...
%     [407:412]   ,NaN,included,thrV,awake,'6X8. poor';...
%     },[],true);

% ID=9;
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [880:884]   ,NaN,included,thrV,awake,'ffgwn.ringy';...
%     [885:889]   ,NaN,included,thrV,awake,'trf';...
%     },[],true);

% ID=12; %%
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1128:1130]   ,NaN,included,thrV,awake,'trf';...
%     [1132]        ,NaN,included,thrV,awake,'sf.look at f0 vs f1';...
%     [1135:1136]   ,NaN,included,thrV,awake,'ffgwn.weak effect';...
%     },[],true);

% ID=13;%%
% subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1182]        ,NaN,included,thrV,awake,'sf.looks weird!';...
%     [1184:1194]   ,NaN,included,thrV,awake,'6x8.largerf at bottom';...
%     [1200:1201]   ,NaN,included,thrV,awake,'rad.shows suppression';...
%     [1203]        ,NaN,included,thrV,awake,'rad.reduced ctr.reduced supp';...
%     },[],true);
% 
% ID=14;
% subj='375'; thrV=[-0.2 Inf 1]; included=1;channels = 1;
% db=db.addSingleUnit(subj,ID,channels,'',{...
%     [1210]   ,NaN,included,thrV,awake,'trf';...
%     [1212:1212]   ,NaN,included,thrV,awake,'sf. likes large gratings';...
%     [1214:1217]   ,NaN,included,thrV,awake,'ffgwn';...
%     [1235:1236]   ,NaN,included,thrV,awake,'or1024. unimpressive';...
%     },[],true);

%%
% db.mode = 'onlyAnalyze';
% db.process([1 9])
% %% reanalyzing
% db.mode = 'onlyAnalyze';
% %splittin ginto multiple separate analyses. #5 seems weird
% % db.process(1:4)
% % db.process(5)
% db.process(14:23)

%% restarting the db
db = neuronDB({'bsNeurons','latest'});
% db.save
db.mode = 'onlyAnalyze';
db.process(21:23) % eerything works. recreating the db

%% 
db = neuronDB('bsNeurons');