function db=initBS(db,mode)
if ~exist('mode','var')||isempty(mode)
    mode = {'latestDB'};
end
switch mode{1}
    case 'latestDB'
        db = db.load('merge_20110219T215221'); % sorted
    case 'inputDB'
        db = db.load(mode{2});
    case 'init'
        ID=1; % neuronID
        awake = 0; %% 1
        anesth = 2.0;
        subj='389'; thrV=[-Inf 0.5 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [7:11]  ,NaN,included,thrV,awake,'trf. good sort';...
            [13:16] ,NaN,included,thrV,awake,'clean spatial.6X8';...
            [17:18] ,NaN,included,thrV,awake,'12X16 still visible';...
            });
        
        ID=ID+1; %% 2
        subj='389'; thrV=[-Inf 0.2 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [21]    ,NaN,included,thrV,awake,'trf. decent sort';...
            [23:27] ,NaN,included,thrV,awake,'6X8. spatial at bottom.';...
            [29]    ,NaN,included,thrV,awake,'sf. unclear peak in sftuning';...
            });
        
        ID=ID+1; %3
        subj='389'; thrV=[-0.2 Inf 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            %[55:57] ,NaN,included,thrV,awake,'good spatial. center and surround';... %removin this because messed up
            [65:67] ,NaN,included,thrV,awake,'6X8. still visible.';...
            });
        
        ID=ID+1; %4
        subj='389'; thrV=[-Inf 0.15 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [72:76] ,NaN,included,thrV,awake,'rf across multiple squares';...
            [85:87] ,NaN,included,thrV,awake,'12X16 after moving';...
            });
        
        ID=ID+1; %5
        subj='375'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [393:397]   ,NaN,included,thrV,awake,'ffgwn';...
            [398:400]   ,NaN,included,thrV,awake,'trf likes high';...
            [402:405]   ,NaN,included,thrV,awake,'sf';...
            [407:412]   ,NaN,included,thrV,awake,'6X8. poor';...
            });
        
        ID=ID+1; %6
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [590:593]   ,NaN,included,thrV,awake,'ffgwn';...
            [595:606]   ,NaN,included,thrV,awake,'decent spatial. incomplete boundary';...
            });
        
        
        ID=ID+1; %7
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [758:761]   ,NaN,included,thrV,awake,'ffgwn. really clean';...
            [763:764]   ,NaN,included,thrV,awake,'sf';...
            [766:769]   ,NaN,included,thrV,awake,'radius. shows suppression';...
            [773:775]   ,NaN,included,thrV,awake,'12X16. shows clear boundaries';...
            [777:778]   ,NaN,included,thrV,awake,'or. unimpressive';...
            [785:794]   ,NaN,included,thrV,awake,'6X8. shows centre and weak surround';...
            });
        
        
        ID=ID+1; %8
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [874 878]   ,NaN,included,thrV,awake,'ffgwn.ringy';...
            });
        
        ID=ID+1; %9
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [880:884]   ,NaN,included,thrV,awake,'ffgwn.ringy';...
            [885:889]   ,NaN,included,thrV,awake,'trf';...
            });
        
        ID=ID+1; %10
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [931:933]   ,NaN,included,thrV,awake,'ffgwn.ringy';...
            });
        
        ID=ID+1; %11
        subj='375'; thrV=[-0.1 Inf 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1008:1015]   ,NaN,included,thrV,awake,'12X16.crappy sort but decent spatial';...
            });
        
        ID=ID+1; %%12
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1128:1130]   ,NaN,included,thrV,awake,'trf';...
            [1132]        ,NaN,included,thrV,awake,'sf.look at f0 vs f1';...
            [1135:1136]   ,NaN,included,thrV,awake,'ffgwn.weak effect';...
            });
        
        
        ID=ID+1;%%13
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1182]        ,NaN,included,thrV,awake,'sf.looks weird!';...
            [1184:1194]   ,NaN,included,thrV,awake,'6x8.largerf at bottom';...
            [1200:1201]   ,NaN,included,thrV,awake,'rad.shows suppression';...
            [1203]        ,NaN,included,thrV,awake,'rad.reduced ctr.reduced supp';...
            });
        
        ID=ID+1;%14
        subj='375'; thrV=[-0.2 Inf 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1210]   ,NaN,included,thrV,awake,'trf';...
            [1212:1212]   ,NaN,included,thrV,awake,'sf. likes large gratings';...
            [1214:1217]   ,NaN,included,thrV,awake,'ffgwn';...
            [1235:1236]   ,NaN,included,thrV,awake,'or1024. unimpressive';...
            });
        
        
        ID=ID+1; %%15
        subj='375'; thrV=[-Inf 0.25 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1277:1281]   ,NaN,included,thrV,awake,'ffgwn';...
            [1283]   ,NaN,included,thrV,awake,'sf. likes small ppc';...
            [1298:1301]   ,NaN,included,thrV,awake,'6X8.changed location a little bit';...
            [1305]   ,NaN,included,thrV,awake,'rad. no suppression';...
            });
        
        ID=ID+1;%16
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1350:1351]   ,NaN,included,thrV,awake,'trf. ylike?';...
            [1353:1359]   ,NaN,included,thrV,awake,'6X8.only at bottom';...
            [1361]   ,NaN,included,thrV,awake,'sf';...
            });
        
        ID=ID+1;%17
        subj='375'; thrV=[-0.2 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1366]   ,NaN,included,thrV,awake,'trf';...
            [1368]   ,NaN,included,thrV,awake,'sf';...
            [1370:1374]   ,NaN,included,thrV,awake,'6x8. at bottom. but complete';...
            [1379]   ,NaN,included,thrV,awake,'rad.suppression';...
            [1381:1382]   ,NaN,included,thrV,awake,'rad.low contrast.suppression?';...
            [1384]   ,NaN,included,thrV,awake,'rad.75 cntr. suppression';...
            [1386:1392]   ,NaN,included,thrV,awake,'6x8. more centered';...
            [1394:1395]   ,NaN,included,thrV,awake,'low ppc.suppression';...
            [1397]   ,NaN,included,thrV,awake,'lower ppc.suppression';...
            });
        
        ID=ID+1;%18
        subj='375'; thrV=[-0.2 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1404:1406]   ,NaN,included,thrV,awake,'trf';...
            [1407:1408]   ,NaN,included,thrV,awake,'sf';...
            });
        
        ID=ID+1;%19
        subj='375'; thrV=[-0.1 Inf 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1414]   ,NaN,included,thrV,awake,'ffgwn.poor sort';...
            });
        
        ID=ID+1;%20
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1622]   ,NaN,included,thrV,awake,'trf.likes 8Hz';...
            });
        
        ID=ID+1;%21
        subj='375'; thrV=[-Inf 0.2 1]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1650]   ,NaN,included,thrV,awake,'trf';...
            });
        
        ID=ID+1;%%22
        subj='375'; thrV=[-Inf 0.2 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1657 1663:1665]   ,NaN,included,thrV,awake,'trf.likes 8Hz';...
            [1671:1672]   ,NaN,included,thrV,awake,'sf.likes small gratings';...
            [1674:1675]   ,NaN,included,thrV,awake,'contrast.look at f0';...
            [1686:1687]   ,NaN,included,thrV,awake,'rad64C100';...
            [1688:1689]   ,NaN,included,thrV,awake,'rad64C80';...
            });
        
        ID=ID+1;%23
        subj='375'; thrV=[-0.25 Inf 2]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [1760]   ,NaN,included,thrV,awake,'trf';...
            [1763]   ,NaN,included,thrV,awake,'sf';...
            [1765]   ,NaN,included,thrV,awake,'radC80PPC128';...
            [1767]   ,NaN,included,thrV,awake,'radC60PPC128';...
            });
        
        ID=ID+1;%24
        subj='257'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [58:68 70:78]   ,NaN,included,thrV,anesth,'ffgwn';...
            [80:113]   ,NaN,included,thrV,anesth,'3X4';...
            [114:127]   ,NaN,included,thrV,anesth,'6X8';...
            });
        
        ID=ID+1;%25
        subj='257'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [151:156]   ,NaN,included,thrV,anesth,'ffgwn';...
            [157:181]   ,NaN,included,thrV,anesth,'3X4';...
            [182:197]   ,NaN,included,thrV,anesth,'6X8?';...
            });
        
        ID=ID+1;%26
        subj='257'; thrV=[-0.12 Inf 0.4]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [388:398 424:436]   ,NaN,included,thrV,anesth,'ffgwn';...
            });
        
        ID=ID+1;%27
        subj='353'; thrV=[-0.2 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [3:5]   ,NaN,included,thrV,anesth,'ffgwn';...
            [25:28]   ,NaN,included,thrV,anesth,'sf';...
            [30:34]   ,NaN,included,thrV,anesth,'or';...
            [59 60 87:90]   ,NaN,included,thrV,anesth,'ffgwn';...
            });
        
        ID=ID+1;%28
        subj='353'; thrV=[-0.2 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'not yet complete',{...
            [160 161 162 164 165]   ,NaN,included,thrV,anesth,'or1024';...
            [167:172]   ,NaN,included,thrV,anesth,'sf';...
            [183:197]   ,NaN,included,thrV,anesth,'6X8';...
            });
        
        ID=ID+1;%29
        subj='353'; thrV=[-0.2 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'not yet complete',{...
            [225:234]   ,NaN,included,thrV,anesth,'or1';...
%             [241:248]   ,NaN,included,thrV,anesth,'or2';...
            [251:253]   ,NaN,included,thrV,anesth,'sf';...
            [265:270]   ,NaN,included,thrV,anesth,'or3';...
            });
        
        ID=ID+1;%30
        subj='354'; thrV=[-0.1 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [20:26]   ,NaN,included,thrV,anesth,'trf';...
            [40 41]   ,NaN,included,thrV,anesth,'or1024';...
            });
        
        ID=ID+1;%31
        subj='354'; thrV=[-0.2 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [53:60]   ,NaN,included,thrV,anesth,'ffgwn';...
            [61 62 64 65]   ,NaN,included,thrV,anesth,'or1024';...
            [67:90]   ,NaN,included,[-0.1 Inf 0.5],anesth,'6X8';...
            });
        
        ID=ID+1;%32
        subj='354'; thrV=[-0.2 Inf 0.5]; included=1;channels = 1;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [120 121 123 124]   ,NaN,included,thrV,anesth,'sf';...
            });
        
        ID=ID+1;%33
        subj='356'; thrV=[-0.05 Inf 0.3]; included=1;channels = 6;
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [110:118]   ,NaN,included,thrV,anesth,'ffgwn';...
            });
        
        ID=ID+1;%34 look at this again
        subj='356'; thrV=[-0.05 Inf 0.3]; included=1;channels = 6; % also 2,9 and 10
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [377:380]   ,NaN,included,thrV,anesth,'some flanker stuff';...
            [397:403]   ,NaN,included,thrV,anesth,'ffgwn';...
            [432:444]   ,NaN,included,thrV,anesth,'spatial';...
            [485 492:498]   ,NaN,included,thrV,anesth,'some flanker stuff';...
%             [492:498]   ,NaN,included,thrV,anesth,'some flanker stuff';...
            });
        
        ID=ID+1;%35
        subj='364'; thrV=[-0.15 Inf 0.4]; included=1;channels = 1; 
        db=db.addSingleUnit(subj,ID,channels,'probably incomplete',{...
            [137:138]   ,NaN,included,thrV,anesth,'sf';...
            });
        
        ID=ID+1;%36
        subj='366'; thrV=[-0.1 Inf 0.5]; included=1;channels = 3; 
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [20:33]   ,NaN,included,thrV,anesth,'ffgwn';...    
            [35:37]   ,NaN,included,thrV,anesth,'sfSin';...
            [38:40]   ,NaN,included,thrV,anesth,'sfSin';...
            [45:47]   ,NaN,included,thrV,anesth,'orGr';...
            [53:72]   ,NaN,included,thrV,anesth,'ffgwn300';...
            [73:91]   ,NaN,included,thrV,anesth,'ffgwn600';...
            });
        
        ID=ID+1;%37
        subj='366'; thrV=[-0.1 Inf 0.5]; included=1;channels = 3; 
        db=db.addSingleUnit(subj,ID,channels,'',{...
            [113:125]   ,NaN,included,thrV,anesth,'ffgwn300';...
            [166:168]   ,NaN,included,thrV,anesth,'or';...
            [193:222]   ,NaN,included,thrV,anesth,'ffgwnSearch';...
            [268:278]   ,NaN,included,thrV,anesth,'or';...
            [328:340]   ,NaN,included,thrV,anesth,'ffgwn';...
            [353:361]   ,NaN,included,thrV,anesth,'or';...
            [367:373]   ,NaN,included,thrV,anesth,'ffgwn';...
            });

    otherwise
        error('unknown mode');
end
end